#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Destroys them (`isoloom down cloud-services`): what they cost stops here.
# The services of `awsgoat-module-2`: the Terraform module `app/modules/module-2`, in the user's aws account.
set -eu
cd "$(dirname "$0")"
here="$(pwd)"
export TF_DATA_DIR="$here/.terraform"
module='../../app/modules/module-2'
terraform -chdir="$module" init -input=false >&2
terraform -chdir="$module" destroy -auto-approve -input=false -state="$here/terraform.tfstate" -var-file="$here/terraform.tfvars.json"
